---
- name: Check running containers
  become: true
  shell: |
    docker container ls -q | wc -l || echo 0
  register: running_containers
  changed_when: false

- name: Restart Docker
  when:
    - running_containers is defined
    - ignore_running_containers or running_containers.stdout|int == 0
  become: true
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Reload Docker daemon configurations
  become: true
  shell: |
    pkill -SIGHUP dockerd

- name: Notify updates of Docker via Slack
  when:
    - slack_token is defined
    - slack_channel is defined
    - slack_icon_url is defined
  environment:
    https_proxy: "{{ http_proxy if http_proxy is defined else '' }}"
  local_action:
    module: slack
    msg: 'The Docker server was updated.'
    token: "{{ slack_token }}"
    channel: "#{{ slack_channel }}"
    username: "{{ ansible_user }}@{{ inventory_hostname }}"
    icon_url: "{{ slack_icon_url }}"
