---
- name: Add Kubernetes repo in Fedora
  when: ansible_distribution == 'Fedora'
  become: true
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  notify: Notify updates of Kubernetes via Slack

- name: Add Kubernetes repo in CentOS
  when: ansible_distribution == 'CentOS'
  become: true
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
  notify: Notify updates of Kubernetes via Slack

- name: Add the GPG key for Kubernetes in Debian
  when: ansible_os_family == 'Debian'
  become: true
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  notify: Notify updates of Kubernetes via Slack

- name: Add Kubernetes repo in Debian
  when: ansible_os_family == 'Debian'
  become: true
  apt_repository:
    repo: "deb [arch=amd64] http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes
  notify: Notify updates of Kubernetes via Slack

- name: Install Kubernetes with dnf
  when: ansible_distribution == 'Fedora'
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - flannel
    - kubeadm
    - kubectl
    - kubelet
  notify: Notify updates of Kubernetes via Slack

- name: Install Kubernetes with yum
  when: ansible_distribution == 'CentOS'
  become: true
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - flannel
    - kubeadm
    - kubectl
    - kubelet
  notify: Notify updates of Kubernetes via Slack

- name: Install Kubernetes with apt
  when: ansible_distribution == 'Ubuntu'
  become: true
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    name: "{{ item }}"
    state: latest
  with_items:
    - flannel
    - kubeadm
    - kubectl
    - kubelet
  notify: Notify updates of Kubernetes via Slack

- name: Set /etc/sysctl.d/k8s.conf
  become: true
  sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_file: /etc/sysctl.d/k8s.conf
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
  notify: Notify updates of Kubernetes via Slack

- name: Start and enable kubelet
  become: true
  systemd:
    name: kubelet
    state: started
    daemon_reload: yes
    enabled: true
  notify: Notify updates of Kubernetes via Slack

- name: Initilize a Kubernetes master node
  when:
    - kubernetes_master is defined
    - inventory_hostname == kubernetes_master
  become: true
  shell: |
    /usr/bin/kubeadm init

- name: Set up a pod network
  when:
    - kubernetes_master is defined
    - inventory_hostname == kubernetes_master
  become: true
  shell: |
    /usr/bin/kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml
    /usr/bin/kubectl taint nodes --all node-role.kubernetes.io/master-
